export const IMAGES = {
    intro: {
        hero: require("../../assets/images/intro/intro-hero.jpg"),
    },
    questions: {
        wolf: require("../../assets/images/questions/Wolf.jpg"),
        lion: require("../../assets/images/questions/Lion.jpg"),
        tiger: require("../../assets/images/questions/Tiger.jpg"),
        lynx: require("../../assets/images/questions/Lynx.jpg"),
        panther: require("../../assets/images/questions/Panther.jpg"),
        bear: require("../../assets/images/questions/Bear.jpg"),
        fox: require("../../assets/images/questions/Fox.jpg"),
        wolverine: require("../../assets/images/questions/Wolverine.jpg"),
        deer: require("../../assets/images/questions/Deer.jpg"),
        monkey: require("../../assets/images/questions/Monkey.jpg"),
        rabbit: require("../../assets/images/questions/Rabbit.jpg"),
        buffalo: require("../../assets/images/questions/Buffalo.jpg"),
        ram: require("../../assets/images/questions/Ram.jpg"),
        capybara: require("../../assets/images/questions/Capybara.jpg"),
        elephant: require("../../assets/images/questions/Elephant.jpg"),
        horse: require("../../assets/images/questions/Horse.jpg"),
        eagle: require("../../assets/images/questions/Eagle.jpg"),
        owl: require("../../assets/images/questions/Owl.jpg"),
        raven: require("../../assets/images/questions/Raven.jpg"),
        parrot: require("../../assets/images/questions/Parrot.jpg"),
        snake: require("../../assets/images/questions/Snake.jpg"),
        crocodile: require("../../assets/images/questions/Crocodile.jpg"),
        turtle: require("../../assets/images/questions/Turtle.jpg"),
    },
} as const;