export const IMAGES = {
    intro: {
        hero: require("../../assets/images/intro/intro-hero.png"),
    },
    questions: {
        wolf: require("../../assets/images/questions/wolf.png"),
        lion: require("../../assets/images/questions/lion.png"),
        tiger: require("../../assets/images/questions/tiger.png"),
        lynx: require("../../assets/images/questions/lynx.png"),
        panther: require("../../assets/images/questions/panther.png"),
        bear: require("../../assets/images/questions/bear.png"),
        fox: require("../../assets/images/questions/fox.png"),
        wolverine: require("../../assets/images/questions/wolverine.png"),
        deer: require("../../assets/images/questions/deer.png"),
        monkey: require("../../assets/images/questions/monkey.png"),
        rabbit: require("../../assets/images/questions/rabbit.png"),
        buffalo: require("../../assets/images/questions/buffalo.png"),
        ram: require("../../assets/images/questions/ram.png"),
        capybara: require("../../assets/images/questions/capybara.png"),
        elephant: require("../../assets/images/questions/elephant.png"),
        horse: require("../../assets/images/questions/horse.png"),
        eagle: require("../../assets/images/questions/eagle.png"),
        owl: require("../../assets/images/questions/owl.png"),
        raven: require("../../assets/images/questions/raven.png"),
        parrot: require("../../assets/images/questions/parrot.png"),
        snake: require("../../assets/images/questions/snake.png"),
        crocodile: require("../../assets/images/questions/crocodile.png"),
        turtle: require("../../assets/images/questions/turtle.png"),
    },
} as const;